- .babelrc
- .eslintrc
- .flowconfig
- .gitignore
- .travis.yml
- package.json
- src/span_context.js
- src/thrift.js
- src/util.js
- test/decls/mocha.js
- test/leaky_bucket_rate_limiter.js
- test/span_context.js
- added span_context and associated tests
- added configuation files and package.json that will be needed
> span context

- package.json
- src/index.js
- src/propagators/binary_codec.js
- src/samplers/probabilistic_sampler.js
- src/span.js
- src/tracer.js
- test/opentracing_compatibility.js
- test/remote_reporter.js
- test/span.js
- test/tracer.js
- test/udp_sender.js
- todo.txt
Works with locally tested opentracing, but will need a new release of opentracing from https://github.com/opentracing/opentracing-javascript/pull/57.
> adapt code to use opentracing interface

- package.json
.gitignore
- make buffer-equal a prod depenency for TestUtils
> - add .npmignore, so that dist will show up even though its in

- entrypoint.js
- src/configuration.js
- test/config/basic_tracer.yaml
- test/config/disable_tracer.yaml
- test/config/tracer_with_reporter_options.yaml
- test/entrypoint.js
- test/init_tracer.js
- jaeger namespace should not be a requirement for the config
> Expose opentracing, and make a config interface change 

- package.json
- src/test_util.js
- test/span_context.js
- test/thrift.js
- test/tracer.js
- test/udp_sender.js
- removed buffer-equal
- removed use of lodash in test-utils
- removed debug-logtron
> Dependency changes:

- src/span.js
- src/tchannel_bridge.js
- src/tracer.js
- test/span.js
- expose property to set name
- expose property to get reporter form tracer
> Extend span and tracer properties

- src/_interfaces/sampler.js
- src/samplers/const_sampler.js
- src/samplers/probabilistic_sampler.js
- src/samplers/ratelimiting_sampler.js
- src/samplers/remote_sampler.js
- src/tracer.js
In preparation for adaptive sampling change
> Pass operation name to samplers

- src/span.js
- src/tracer.js
- test/tracer.js
- test/udp_sender.js
> Stop double reporting tracer tags

- src/rate_limiter.js
- src/samplers/ratelimiting_sampler.js
- test/rate_limiter.js
- test/samplers/ratelimiting_sampler_test.js
Fix bug where if the creditsPerSecond < itemCost, the leaky bucket never fills up. Added a maxBalance to set the upperbound of the balance.
> Fix leaky bucket bug

- src/constants.js
- src/span_context.js
- src/tracer.js
- test/span.js
This reverts commit 7bb07a381b115b0539c5996646edb6650aea18ff.
> Revert "Revert "Add support for deferred sampling (#107)" (#113)"

- CHANGELOG.md
- src/span.js
- test/span.js
See: https://github.com/uber/jaeger-client-java/pull/189
> Save baggage in span logs

- src/rate_limiter.js
- test/rate_limiter.js
- test/samplers/all_samplers.js
- test/samplers/guaranteed_throughput_sampler.js
- test/samplers/ratelimiting_sampler_test.js
> Randomize rater limiter balance on initialization

- .gitignore
- crossdock/docker-compose.yml
- crossdock/rules.mk
- crossdock/src/endtoend_handler.js
Signed-off-by: Pavol Loffay <ploffay@redhat.com>
> Xdock use jaeger compose

- CHANGELOG.md
> Release v3.6.0

- package.json
- src/_flow/bufrw.js
- src/reporters/udp_sender.js
- test/udp_sender.js
Kinda fixes https://github.com/jaegertracing/jaeger-client-node/issues/181 in that it elucidates why the spanSize is undefined.
> Log error when Thrift conversion fails

- .travis.yml
- package.json
> Remove test-ci script

- .travis.yml
> Update node versions specified in .travis.yml

- src/reporters/remote_reporter.js
- test/remote_reporter.js
> Flush only if process is set

- src/reporters/remote_reporter.js
Part of https://github.com/jaegertracing/jaeger/issues/151
> Change default flush interval to 1sec

- .babelrc
- .travis.yml
- Makefile
- crossdock/docker-compose.yml
- package.json
Use babel-preset-env instead of babel-preset-2015
Resolves #154
> Edit travis.yml, Travis always builds on node 4

- Makefile
> Edit test script in Makefile

- CHANGELOG.md
- package.json
> Preparing release 3.8.0

- .prettierrc
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- package.json
and I also increased the width for `.json` files to make them look nicer for long ling scripts
> Prettier Markdown files

- README.md
Fix #147
Signed-off-by: Yuri Shkuro <ys@uber.com>
> Explain how to use metrics and logger

- .travis.yml
- Makefile
Signed-off-by: Yuri Shkuro <ys@uber.com>
> Add travis_retry before npm install

- .travis.yml
Resolves #236
Signed-off-by: Yuri Shkuro <ys@uber.com>
> Stop testing with Node 0.12

- CONTRIBUTING.md
refs https://github.com/jaegertracing/jaeger/issues/771
Signed-off-by: Eundoo Song <eundoo.song@gmail.com>
> Use different "good commit message" reference and inline it 

- src/metrics/metrics.js
- src/samplers/remote_sampler.js
- src/tracer.js
- test/samplers/remote_sampler.js
- test/tracer.js
This makes metrics consistent with the other clients 
Resolves #178 
Signed-off-by: Eundoo Song <eundoo.song@gmail.com>
> Make metrics consistent

- src/_flow/throttler.js
- src/constants.js
- src/throttler/remote_throttler.js
- src/tracer.js
- test/lib/config_server.js
- test/throttler/remote_throttler.js
- test/udp_sender.js
- The throttler API seems to have changed since I last tested this, updating to conform.
> Fix throttler API

- CHANGELOG.md
- package.json
> Preparing release v3.11.0

- CHANGELOG.md
- package.json
> Back to development

- test/tracer.js
A regression in test coverage.
Bolsters `tracer.js` coverage after removing [test cases](https://github.com/jaegertracing/jaeger-client-node/pull/280/files#diff-4abc69534f2675ef27d324a3a3a87638L125) from UDPSender which did not test anything in UDPSender.
> Bolster tracer.js coverage per UDPSender cleanup

- README.md
> Add HTTP sender documentation

- CHANGELOG.md
- package.json
> Preparing release 3.13.0

- src/reporters/logging_reporter.js
> Add setProcess method to LoggingReporter (#300)

- src/configuration.js
- src/configuration_env.js
- src/samplers/remote_sampler.js
- test/init_tracer.js
Rename variables according to common names from https://www.jaegertracing.io/docs/1.8/client-features/
> Use common env variables

- .travis.yml
- src/tracer.js
- test/tracer.js
Fixes https://github.com/jaegertracing/jaeger-client-node/issues/335
- Check if there's already a value before using the default logic
> Use the ip and hostname tags if provided

- CHANGELOG.md
- package.json
> Preparing release 3.14.0

- src/reporters/http_sender.js
Signed-off-by: Sergey Skupoy <sergey.skupoy@gmail.com>
- Fixes memory leak caused by unconsumed response body.
- Just resume() response to free up memory
> Fix HTTP sender, consume response data to free up memory

- CHANGELOG.md
- package.json
> Prepare v3.15.0 release

- package-lock.json
- src/samplers/probabilistic_sampler.js
- test/samplers/all_samplers.js
> Fix incorrect error message

- .github/workflows/ci-crossdock.yml
- .github/workflows/ci-unit-tests.yml
- README.md
- crossdock/docker-compose.yml
- scripts/publish-crossdock.sh
- #452
- avoid building crossdock image the second time
- only publish crossdock image if test run was successful
- add missing `npm run cover`
- update build badge in the README
> Clean-up GitHub Actions
