Makefile, README.md, benchmarks/flame_graph_loop.js, benchmarks/span_context.js, dist/package.json, dist/src/constants.js, dist/src/reporters/udp_sender.js, dist/src/span_context.js, dist/src/test_util.js, package.json, src/span_context.js, test/span.js, test/span_context.js, test/tracer.js
According to the basic server-client loop `benchmarks/flame_graph_loop.js` flamegraph, to/from strings ops on the span context are among the most expensive portions.  This change introduces a dual representation of trace IDs as `string` and `Buffer`. Whichever is available first is stored, and the other is only generated as needed. For most (unsampled) spans the `fromString` operation produces string IDs, and the outbound `toString` operation can use them as is, without even converting to `Buffer` representation, which is more expensive.
The micro-benchmarks below show almost 10 times improvement for to/from string methods.
```
$ node ./benchmarks/span_context.js
Beginning Span Context Benchmark...
2 tests completed.
SpanContext:fromString x   274,035 ops/sec ±1.03% (90 runs sampled) …
```
=> Use lazy dual string/Buffer representation for trace IDs

src/tracer.js, test/tracer.js
baggage context was passed to startSpan.
=> Sample span even when it is manually passed baggage/debug-id

src/span.js, src/span_context.js, src/tracer.js, test/span.js
This preserves adaptive sampling by allowing a proper operationName
to be correlated with the correct sampling rate (eventhough the
sampling decision has already happened.)
=> Re-sample the span when operationName is set after span creation

src/span.js, src/thrift.js, src/tracer.js, src/util.js, test/span.js, test/test_util.js, test/thrift.js, test/tracer.js
opentracing-javascript API states that external timestamps can be passed expressed in milliseconds since epoch. We can convert to microseconds only when reporting to the backend.
=> Accept external timestamps in milliseconds since epoch

CHANGELOG.md, package.json, src/configuration.js, test/init_tracer.js
Metrics is an internal class, MetricsFactory is what we expect users to provide.
=> Make Configuration accept MetricsFactory, not Metrics

src/propagators/text_map_codec.js, test/propagators.js
decodeURIComponent can throw `URIError: URI malformed` when unable to parse the string.
The string representation of the context is #:#:#:# (# is hex digits), so it is "safe" to be used as is in the http header value without URL encoding.
=> Protect from exceptions in decodeURIComponent; do not url-encode span context

src/constants.js, src/span_context.js, src/tracer.js, test/span.js
- When a downstream service doesn't have enough information to
make a sampling decision, it sets the span context flag 4.
- When a span with the flag 4 is encountered, a sampling decision
for any child spans is made based on the current operation name
instead of depending on the sampling decision on the parent if
the span context doesn't contain the debug flag(2). Debug spans
are always sampled.
=> Add support for deferred sampling

src/constants.js, src/span_context.js, src/tracer.js, test/span.js
This reverts commit caac859468d29db6932a4923f5bb6ca2cd5513f0.
Reverting deferred sampling to release a bug fix.
=> Revert "Add support for deferred sampling (#107)"

crossdock/test/endtoend_handler.js, src/reporters/udp_sender.js, src/thriftrw-idl/agent.thrift, test/udp_sender.js
Bumping jaeger-idl broke some things. Before `jaeger.idl` had the emitBatch function but it was moved to `agent.idl`; however, `agent.idl` is not thriftrw compatible.
I added a new `agent.idl` that's thriftrw compatible, but it has to be manually updated to keep up to date. The thriftrw idl could be moved to jaeger-idl repo however it's only nodejs specific.
=> Bump jaeger idl

src/reporters/udp_sender.js, src/tracer.js, test/udp_sender.js
=> Uncaught exception from finish()

package.json, src/_flow/socket.js, src/configuration.js, src/reporters/udp_sender.js, test/udp_sender.js
=> Fix buffer size counting bug and add logging to UDP sender

package.json, src/reporters/logging_reporter.js, test/all_reporters.js
=> Log only span context

Makefile, crossdock/test/endtoend_handler.js, src/reporters/udp_sender.js, src/thriftrw-idl/agent.thrift, test/udp_sender.js
Fix #155.
- Fix include in `thriftrw-idl/agent.thrift` to assume PWD is the location of the `agent.thrift`
- Init `thriftrw-idl/agent.thrift` via entryPoint (updated tests, too)
- Copy `thriftrw-idl/agent.thrift` to dist when building
=> Copy thriftrw-idl to dist, fix include, init via entryPoint

src/samplers/guaranteed_throughput_sampler.js, src/samplers/ratelimiting_sampler.js, src/samplers/remote_sampler.js, test/samplers/all_samplers.js, test/samplers/guaranteed_throughput_sampler.js, test/samplers/ratelimiting_sampler_test.js, test/samplers/remote_sampler.js
The RateLimitingSampler is always recreated when the tracesPerSecond is updated. This forces the RateLimitingSampler to always sample on a sampling strategy update. If the number of instances for a service is in the thousands, this will generate thousands of sampled traces. This fix only updates the tracesPerSecond but keeps the balance intact to reduce the impact of a sampling strategy update.
=> Use RateLimitingSampler.update()

README.md, entrypoint.js, src/propagators/baggage.js, src/propagators/text_map_codec.js, src/propagators/zipkin_b3_text_map_codec.js, test/propagators.js, test/zipkin_b3_text_map_codec.js
This PR addresses #165 by adding a new text map codec.  
The new codec (named `ZipkinB3TextMapCodec`) injects and extracts the relevant `X-B3-*` headers used by zipkin, according to [the zipkin spec](https://github.com/openzipkin/b3-propagation).
The new codec can be used by registering it with a tracer instance as both an injector and an extractor:
```
let codec = new ZipkinB3TextMapCodec({                                                            
urlEncoding: true                                                                          
}); 
tracer.registerInjector(opentracing.FORMAT_HTTP_HEADERS, codec);                                  
tracer.registerExtractor(opentracing.FORMAT_HTTP_HEADERS, codec);
```
In order to accomodate this functionality, I added this new codec (as well as …
=> Adds support for the Zipkin HTTP B3 propagation format

CHANGELOG.md, package.json
[Per the release instructions](https://github.com/jaegertracing/jaeger-client-node/blob/master/RELEASE.md), this PR prepares for release 3.7.0.  This is a minor version increment, to add the changes contained in #175.
=> Preparing release 3.7.0

package.json
Remove dev dependency that is no longer maintained
Cf. #183
=> Remove "babel-node-debug" dev dependency

.travis.yml, src/configuration.js, test/init_tracer.js
This was the cause of https://github.com/jaegertracing/jaeger-client-node/issues/181
Since serviceName is not provided, the jaeger batch to thrift conversion fails.
=> Throw error if serviceName is not provided

CONTRIBUTING.md
=> Remove unnecessary 'make build-node' step in developing instructions

src/reporters/composite_reporter.js, src/reporters/remote_reporter.js, src/reporters/udp_sender.js, test/all_reporters.js, test/remote_reporter.js, test/udp_sender.js
Flushes spans properly to backend
=> Use callbacks in UDPSender and remoteReporter

.flowconfig, src/_flow/reporter.js, src/reporters/composite_reporter.js, src/reporters/in_memory_reporter.js, src/reporters/logging_reporter.js, src/reporters/noop_reporter.js, src/reporters/remote_reporter.js, src/reporters/udp_sender.js, test/all_reporters.js, test/remote_reporter.js, test/udp_sender.js
* Add proper type signatures to UDPSender and Reporter callbacks (instead of `?Function`)
* Define sender callbacks as `(numSpans: number, err?: string) => void` instead of passing a `SenderResponse` object (avoids unnecessary memory allocation)
* Remove logging from UDPSender, instead return the error to the reporter that logs it
* Fix the tests (`done()` was called in the middle of some tests, aborting them prematurely)
Follow up to #224
Resolves #214 
Resolves #157 
Resolves #32 
Supersedes #166
=> Change UDPSender callbacks to (numSpans: number, err?: string) => void

package.json
=> Add engines field to package.json

.travis.yml, Makefile
* only lint with Node 6.x as the primary dev version
* reorder travis matrix to run critical tasks first
Signed-off-by: Yuri Shkuro <ys@uber.com>
=> Require Node 6.x for building

src/configuration.js, test/init_tracer.js
When remote reporter and sampler are initialized via _getReporter and _getSampler, logger and metrics options are not passed into each constructor. 
Signed-off-by: eundoo-song <eundoo.song@samsung.com>
=> Pass logger/metrics option to remote sampler,reporter

src/rate_limiter.js, test/init_tracer.js, test/rate_limiter.js, test/throttler/remote_throttler.js, test/udp_sender.js
The current update function truncates the balance on update instead of scaling it proportionally with respect to the old range and the new range. By scaling, we maintain the randomness in the balances across clients.
=> Update RateLimiter to scale credits on update

src/metrics/prometheus.js
Signed-off-by: Eundoo Song <eundoo.song@gmail.com>
- This removes prom-client warning called when a metric is constructed.
- Passing a non-object to metrics constructor is deprecated. So it shows below warning when a metric is constructed.
```
(node:49239) DeprecationWarning: prom-client - Passing a non-object to metrics constructor is deprecated
```
prom-client code : https://github.com/siimon/prom-client/blob/v11.0.0/lib/counter.js#L30,L42
=> Pass object to prom-client metric to fix warning

src/throttler/remote_throttler.js, test/throttler/default_throttler.js, test/throttler/remote_throttler.js
@black-adder how did these files end up with MIT license? Was it added automatically somehow?
=> Fix license to Apache on new files

src/metrics/metrics.js
- When using `prom-client` as in the example
```
/Users/yknx4/Projects/price-tracker/node_modules/prom-client/lib/counter.js:60
throw new Error('Invalid metric name');
^
Error: Invalid metric name
at new Counter (/Users/yknx4/Projects/price-tracker/node_modules/prom-client/lib/counter.js:60:10)
at PrometheusMetricsFactory._createMetric (/Users/yknx4/Projects/price-tracker/node_modules/jaeger-client/dist/src/metrics/prometheus.js:102:28)
at PrometheusMetricsFactory.createCounter (/Users/yknx4/Projects/price-tracker/node_modules/jaeger-client/dist/src/metrics/prometheus.js:117:42)
at new Metrics (/Users/yknx4/Projects/price-tracker/node_modules/jaeger-client/dist/src/metrics/metrics.js:100:47)
at Object.initTracer (/Users/yknx4/Projects/price-tracker/node_modules/jaeger-client/dist/src/confi …
```
=> Fix Invalid metric name: Rename throttler-update to throttler_update

src/configuration.js, src/reporters/http_sender.js, src/reporters/sender_utils.js, src/reporters/udp_sender.js, test/http_sender.js, test/init_tracer.js, test/udp_sender.js
This will use the Jaeger collector HTTP endpoint (assumed to be running
on localhost) by default, but is configurable to send Thrift-encoded
spans to any HTTP endpoint.
Spans are batched upto a certain amount (based on # of spans and not
byte lengths) and are also flushed on a regular interval by the
RemoteReporter just like with the UDPSender.
It also supports basic auth in case the Jaeger collector has some form
of authentication in front of it.
Fixes #170
Signed-off-by: Ben Keith <bkeith@signalfx.com>
=> Add HTTP Sender

src/metrics/metrics.js
- Fix inconsistency seen here: https://github.com/jaegertracing/jaeger-client-node/pull/279/files#r209324272
No tests need to updated because we mock metrics, we would need to introduce a local metric store (maybe use prometheus?) to test against the actual metric.
=> Rename 'throttler_update' metric to 'throttler_updates'

src/reporters/http_sender.js, test/http_sender.js
The http.Agent instance doesn't work with HTTPS and requires a separate type of agent.
=> Fix HTTP sender to work with TLS

README.md
Signed-off-by: kanolato <kanolato@gmail.com>
- I spent a while going over the docs and reading the code trying to figure out how to configure opentracing + jaeger node client to send spans to the local jaeger instance, until i found [this](https://stackoverflow.com/questions/47706011/jaeger-back-end-isnt-recieving-any-data-using-jager-node-js-client)
- Main README updated with sampler configuration
=> Sampler documentation

src/reporters/http_sender.js
This feels more backwards compatible. Maybe `url.protocol == 'http'` is guaranteed, I don't know, but I would rather it fail when it's not https (meaning it's no worse than in the previous release) than fail for regular http.
=> Swap https/http order

src/configuration.js, src/tracer.js, test/init_tracer.js
=> Add missed contextKey option to initTracer

src/propagators/zipkin_b3_text_map_codec.js, test/zipkin_b3_text_map_codec.js
Since HTTP headers are case insensitive and title case is often used,
If we have a carrier that has **not** lower case B3 Zipkin headers - we'll get an `undefined` value or a `TypeError`.
E.g.:
```js
const carrier = {
'X-B3-TraceId': '123456',
// ...
};
// extract the context
const context = tracer.extract(opentracing.FORMAT_HTTP_HEADERS, headers);
```
Here lower case name for the `TraceId` B3 header will match the `ZIPKIN_TRACE_HEADER` constant
but the carrier doesn't actually have `carrier[ZIPKIN_TRACE_HEADER]` key.
This will lead to the following unexpected behavior:
- if `urlEncoding` is set to `false` - `context.traceId` getter will be `undefined`;
- if `urlEncoding` is set to `true` - `context.traceId` getter will throw `TypeError: Cannot read property 'indexOf' of undefined` . …
=> Makes zipkin codec work with case insensitive headers.

src/propagators/text_map_codec.js, src/propagators/zipkin_b3_text_map_codec.js, src/span.js, src/tchannel_bridge.js, src/test_util.js, src/util.js, test/tracer.js
Signed-off-by: Geoffrey Goodman <ggoodman@gmail.com>
Resolves #317
Changes calls that expect different user-supplied objects to be prototypical objects to more defensive calls using `Object.prototype.hasOwnProperty.call`.
=> Support injecting and extracting into carriers without Object prototypes

src/configuration_env.js
=> Warning for mismatching env variables

src/tchannel_bridge.js, test/tchannel_bridge.js
Signed-off-by: Varsha <varsha.verma.eee15@itbhu.ac.in>
- Fixes #251 
- event and message key value pairs added in accordance with the opentracing conventions
=> Make TchannelBridge use semantic conventions when logging error to the span

src/tracer.js, src/util.js, test/tracer.js, test/util.js
- Standardize process.ip field . After discussion on mailinglist (https://groups.google.com/forum/#!topic/jaeger-tracing/T7pIa_jkcaU), the node client will send ip in dot format and not in signed int32.
=> Transform IP from int32 representation to dot representation

src/propagators/zipkin_b3_text_map_codec.js, test/zipkin_b3_text_map_codec.js
The sampling state headers can have three possible values; force sampling, deny sampling, and defer sampling decision. The B3 propagator only looks at the existence of the header, and thus always forces sampling, even when the value is falsy.
> An accept sampling decision is encoded as `X-B3-Sampled: 1` and a deny as `X-B3-Sampled: 0`. Absent means defer the decision to the receiver of this header. For example, a Sampled header might look like: `X-B3-Sampled: 1`.
> 
> Note: Before this specification was written, some tracers propagated `X-B3-Sampled` as `true` or `false` as opposed to `1` or `0`. While you shouldn't encode `X-B3-Sampled` as `true` or `false`, a lenient implementation may accept them.
https://github.com/openzipkin/b3-propagation#sampling-state-1
Check that the value is …
=> Support false values for the B3 Sampled header

Makefile, RELEASE.md, src/tracer.js, src/version.js
- Resolves #338 
- Makefile creates dist/src/tracer.js with version from package.json instead of a hardcoded value.
- Add src/version.js with stand in version.
- Change the version in dist/src/version.js to be version from package.json.
=> Update make build-node to feed version to src/tracer.js

src/tracer.js, test/tracer.js
Signed-off-by: Anton Fedorov <fapspirit@gmail.com>
- Fixes mutation of tags provided by user (see #345 for more info)
- Clone `options.tags` before assignment due to unnecessary mutations inside `Tracer`
=> Avoid mutation of user's tags

.nvmrc, .travis.yml, Makefile, package-lock.json, package.json, src/configuration_env.js
Fix #363.
Use the current LTS version of node (see [releases](https://nodejs.org/en/about/releases/)).
This adds adds a package-lock.json and causes two prettier formatting changes.
=> Fix install / build by using latest LTS node

Makefile, package-lock.json
Publish omits the `dist/` folder.
Remove unused `dist/package.json`, which was the cause of publish failing. The `dist/package.json` was being interpretted as the root of a different package, which caused npm to omit everything in `dist/` when publishing. Removing this file should resolve the publish issues. 
_Note: package.json was previously used to extract the current version of the node client, at runtime. That is now extracted from `dist/src/version.js` which is generated at build-time from `package.json#version`._
=> Fix npm publish, rm unused dist/package.json

src/samplers/remote_sampler.js, test/samplers/remote_sampler.js
- Allows users to specify a custom sampling endpoint on the agent so that they may experiment easily.
- Add a configuration that takes in sampling path, defaulting to `/sampling`
=> Support configuring sampling url

src/span_context.js, test/span_context.js, test/tracer.js
Resolves #386
Signed-off-by: Prithvi Raj <p.r@uber.com>
=> Initialize SpanContext.parentId to `null`

src/index.js, test/samplers/exp_priority_sampler.js, test/samplers/exp_tag_sampler.js
test should be using import from index whenever possible for types that are supposed to be public
=> Export experimental samplers via index

test/http_sender.js, test/propagators.js, test/samplers/all_samplers.js, test/samplers/guaranteed_throughput_sampler.js, test/samplers/rate_limiting_sampler.js, test/span_context.js, test/tchannel_bridge.js, test/test_util.js, test/text_map_codec.js, test/throttler/default_throttler.js, test/throttler/remote_throttler.js, test/tracer.js, test/udp_sender.js, test/zipkin_b3_text_map_codec.js
`assert.isNotOk` can match too many conditions, sometimes giving false positives in the tests.
Change to use more precise asserts, like isFalse when checking boolean fields.
=> Use more precise tests than isNotOk

src/span.js, test/all_reporters.js, test/http_sender.js, test/remote_reporter.js, test/samplers/all_samplers.js, test/samplers/exp_priority_sampler.js, test/samplers/exp_tag_sampler.js, test/samplers/guaranteed_throughput_sampler.js, test/samplers/rate_limiting_sampler.js, test/samplers/remote_sampler.js, test/span.js, test/span_context.js, test/tchannel_bridge.js, test/test_util.js, test/text_map_codec.js, test/throttler/default_throttler.js, test/throttler/remote_throttler.js, test/tracer.js, test/udp_sender.js, test/zipkin_b3_text_map_codec.js
assert.isOk can match too many conditions, sometimes giving false positives in the tests.
Change to use more precise asserts, like isTrue when checking boolean fields.
=> Use more precise tests than isOk

src/configuration.js, src/tracer.js, test/tracer.js
Signed-off-by: Jonathan Monette <jon.monette@gmail.com>
- Fixes: #400 
- Added a configuration option to share the parendId and spanId between the child and parent for span.kind=rpc.  This was already implemented in the java tracer but the node tracer seems to be missing this option.   Java configuration for reference: https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerTracer.java#L613-L616
=> Add option to share the ids from the parent for rpc servers

src/reporters/composite_reporter.js, src/reporters/in_memory_reporter.js, src/reporters/logging_reporter.js, src/reporters/noop_reporter.js, src/reporters/remote_reporter.js, test/all_reporters.js
Resolves #402
Signed-off-by: Andrea Di Giorgi <andrea.digiorgi@joinhoney.com>
=> Add toString to reporters

src/samplers/per_operation_sampler.js, test/samplers/remote_sampler.js
Per-operation adaptive sampling should only apply to service endpoints, not to operation names of the inner/children spans. Recent changes (e.g. #380) broke that functionality and traces can now be sampled by the per-operation sampler triggering on children spans. This is a problem for adaptive sampling backend that only records operations from the root spans, meaning all child operations are getting the default probability, which may be higher than the calculated probabilities.
- Add a test that demonstrates the problem.
- Change per-operation sampler to only allow sampling "local root spans", which is equivalent to the actual root span of the trace because spans with remote parent are finalized right away.
=> Do not apply adaptive sampler to child spans

src/reporters/http_sender.js, test/http_sender.js
Resolves #414 
HTTPSender empty the send queue when catch error to avoid OOM
=> [HTTPSender] Clear span buffer if Thrift encoding fails

crossdock/Dockerfile
Fix for crossdock tests failing with
```
node_1         |     at Function.Module._load (module.js:311:12)
node_1         |     at Module.require (module.js:366:17)
node_1         |     at require (module.js:385:17)
node_1         |     at Object.<anonymous> (/node_modules/tchannel/v2/index.js:44:12)
node_1         | /node_modules/tchannel/v2/call.js:49
node_1         | var CN_VALUE = bufferFrom('cn').readUInt16BE(0, false);
node_1         |                ^
node_1         | 
node_1         | TypeError: this is not a typed array.
node_1         |     at from (native)
node_1         |     at Object.<anonymous> (/node_modules/tchannel/v2/call.js:49:16)
node_1         |     at Module._compile (module.js:435:26)
node_1         |     at Module._extensions..js (module.js:442:10)
node_1         | …
```
=> Pin tchannel to v3 for crossdock test

src/span_context.js, test/span_context.js
Signed-off-by: Sandes de Silva <sandes.samararatne@gmail.com>
- https://github.com/jaegertracing/jaeger-client-node/issues/406
- Add opentracing `toSpanId` and `toTraceId` methods to retrieve span ID and trace ID's respectively
=> feat(span-context): add open tracing methods to get span and trace id

README.md
Signed-off-by: Justin Walz <justin.walz10@gmail.com>
Resolves https://github.com/jaegertracing/jaeger-client-node/issues/293
- I noticed that calling close() resolved some issues I was having locally, and found this ticket which is somewhat related https://github.com/jaegertracing/jaeger-client-node/issues/293.
- Updated the README to include notes on these two pieces (flush interval and tracer.close().
=> Document trace buffer flush interval and close

crossdock/src/helpers.js, crossdock/src/http_server.js, crossdock/src/tchannel_server.js, crossdock/test/tchannel_server.js, package-lock.json, package.json, src/configuration.js, src/tchannel_bridge.js, src/test_util.js, src/thrift.js, test/http_sender.js, test/init_tracer.js, test/opentracing_compatibility.js, test/tchannel_bridge.js, test/test_util.js, test/text_map_codec.js, test/thrift.js, test/udp_sender.js, test/zipkin_b3_text_map_codec.js
There is a potentially breaking change in 0.14
https://github.com/opentracing/opentracing-javascript/issues/79
Need to see how this will affect 0.10 JS code.
=> Upgrade to opentracing-javascript 0.14

crossdock/Dockerfile
- The builds started failing because the Docker image `woorank/docker-node-babel` used by crossdock build disappeared from Docker Hub.
- I republished the copy of the image from my local repository. It is not clear what kind of image it was, probably built with Node 0.10 and an older version of Babel. It also seems to include Python2 without which the crossdock `docker build` fails now.
=> Replace docker-node-babel image that disappeared from Docker Hub

README.md, src/reporters/http_sender.js, src/reporters/udp_sender.js, src/thrift.js, test/http_sender.js
Always reading the jaeger thrift definition file from the root dir (i.e. `src`) allows consumers to bundle `jaeger-client`, e.g. for uploading code to an AWS lambda function.
To bundle `jaeger-client` with `webpack` for example, the thrift file needs to be copied into the output directory of the bundle like this:
```js
{
plugins: [
new CopyPlugin([
{
from: require.resolve(
'jaeger-client/dist/src/jaeger-idl/thrift/jaeger.thrift'
),
to: 'jaeger-idl/thrift/jaeger.thrift'
}
])
]
}
```
With this in place `fs.readFileSync` will be able to find the file.
Signed-off-by: Hendrik Liebau <mail@hendrik-liebau.de>
=> Always read thrift defs from `./` to better support bundling

package-lock.json, package.json
Resolves #422 
When applications that use this module start with recent Node versions, a deprecation warning relating to `Buffer` is emitted. This is caused by the xorshift dependency.
There may be other deprecated Buffer usages, but only the first one will be logged. So I'm starting here.
I upgraded xorshift to the lastest version, which doesn't make use of `Buffer` at all (and also doesn't rely on new dependencies for compatibility).
=> Fix xorshift related deprection warning (resolves #422)

.github/workflows/ci-crossdock.yml, .github/workflows/ci-unit-tests.yml, .nvmrc, Makefile, crossdock/Dockerfile, crossdock/rules.mk, crossdock/src/driver.sh, package-lock.json, package.json
- the CI no longer succeeds with Node 4
- v10 is EOL in a few days
- upgrade tchannel to 4.x to remove dependency on Node 0.10 (YAY!)
- remove all Node versions earlier than v10; add versions 12, 14, 16
- make Node v14 the primary
- use official node/14-alpine base image for crossdock instead of hacky `jaegertracing/xdock-node:docker-node-babel` which has no source (see #439)
- turns out doing npm install is not that slow in Docker
- clean-up GH actions and Make targets which had many unnecessary installs/uninstalls
=> Stop testing with Node <v10; upgrade tchannel->4.x

src/configuration_env.js, test/init_tracer.js
Signed-off-by: Gerrit Kieffer <kieffer.gerrit@gmail.com>
- Resolves #460
- This is a re-issue of #461 (due to an incorrect source branch)
- Replace implicit boolean evaluation with explicit check in ternary operator / number check
=> Fix env parsing of falsy values (#460)

src/reporters/http_sender.js, test/http_sender.js
Fixes the issue where the server might respond with an error (4xx, 5xx) but no feedback is given to the developer that can help them diagnose the issue.
Resolves #458
- Uses the same pattern as on socket errors: builds an error message and calls the `logger.error()` method, as well as providing the error to the flush callback function.
=> Report HTTP errors when flushing spans

package-lock.json, package.json, src/tracer.js
Projects using `jaeger-client` cannot use `uuid` because of breaking changes since v3.x
- Update uuid to latest stable version
=> Update uuid package to latest stable version

README.md, crossdock/test/endtoend_handler.js, src/reporters/udp_sender.js, src/thrift.js, test/udp_sender.js
Bundling with webpack / esbuild is hard due to the use of `__dirname + "../"` for the udp sender.
Add a helper function in src/thrift.js that returns an absolute path to
agent.thrift, without using "../". This is done to simplify bundling with
webpack or esbuild: assume an app is bundled to /app/index.js, if we resolve
a path to "../thrift-idl/etc", the file will be loaded from /thrift-idl/etc,
which is at the root of the filesystem.
Adjust README to support udp-sender.
This commit is a continuation of #441.
=> Simplify bundling udp_sender
